name = "metabayn-backend"
main = "src/index.ts"
compatibility_date = "2024-09-26"
keep_vars = true

# Binding Database D1
[[d1_databases]]
binding = "DB"
database_name = "metabayn-db"
database_id = "0869e5b4-5279-4a47-8b1e-f2762e93eaee"

[ai]
binding = "AI"

[triggers]
crons = ["0 * * * *"]

[vars]
PROFIT_MULTIPLIER = 1.6
